name: Comprobar que existe index.html

on:
  push:
    branches:
      - main
      - master
      - "*"

jobs:
  check-required-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Verificar que existe index.html
        run: |
          if [ -f "index.html" ]; then
            echo "✅ El archivo index.html existe."
          else
            echo "❌ El archivo index.html NO existe."
            exit 1
          fi